### ISSUE TITLE
Hello :)

### ISSUE THREAD

**Issue by PathForgingStudios** [azakhi/GDModdingTool#3]
First of all thank you so much for this!!

I have succeeded in modifying the main game using the instructions you provided.

But now I want to modify an existing mod (Dawn of Masteries), and I have tried many different things using your instructions, but nothing worked. Everytime I opened the custom map, the character UI, masteries UI, etc are kinda messed up.

Can you help me? Thanks!

**Comment by azakhi** [comment]
Hello,
Can you share your config file and the logs please? Also let me know how you did it step by step.

**Comment by PathForgingStudios** [comment]
> Hello, Can you share your config file and the logs please? Also let me know how you did it step by step.

Hi! So first of all, I tried many different ways, using specifically all the steps you mentioned.

So I will specify which steps I used, the ones I think should work from what I understood, since you mentioned some were optionals, to try to modify an existing mod. Just some basics stuff like XP multiplier and Attributes points per level, etc. Just to see straight away if it works or not. And like I said, it worked well for a custom map of its own, but not when I try to modify another mod using your method.

**Setting Up**

So first I, copied the ExtractFiles.bat into the game folder itself, because if I open this program outside of this folder, no matter what path I specify the Grim Dawn.exe to, and the output folder to, it keep saying that it can’t find the Template.Arc and Database.Arz (See picture 00 and 01). So I opened it from the game folder itself, click enter on both place and it worked perfectly.

So once that done, the folders “records” and “templates” are created under the database folder, records having 662 Mo and templates having 4,12 Mo. (see picture 02)

So after the Setting up Grim Dawn for Modding part, I skipped the Creating a New Mod part, since it says optional. And I go to Configuration File and Customizations.

**Configuration File and Optimizations**

So I copied the Config_SmashNGrabLike.txt and renamed it Config.txt and placed it into your main GDModdingTool folder. I modified it so that I only have 3 commands, which I should be able to see quickly if they worked right from level 2. (see picture 03)

I used $AdditionalRecordsDirectory because this seemed to be the option to use if I want to modify another mod. In the path name I changed “MyCustomMod” to “dom” since “dom” is the name folder of Dawn of Masteries Mod. I thought this was the way to go, but maybe I am wrong here. 
Also, I realized that in the “database” folder from “dom” folder, there is no “records” folder, only a file named dom.arz so I have to create it. I found that strange so maybe this is where something is not right. Also, there is a folder called “resources”, I don’t know if that’s of any importance. (see picture 04)
As for the output directory I left it as it is under the same folder name you wrote which is “test” folder. And for the Source Subdirectories I left it as it is also. And for the final Customization parts, I think everything is written correctly in the config.txt. I used extreme numbers for the customizations just to quickly see straight away if it works. Like the XP should augment drastically high as soon as I kill one monster.

**Running Program**

So I opened the GDModdingTool.exe and everything worked perfectly. Though scanning the files took much longer this time than Friday.  (See pictures 05)
So as the final steps, I opened AssetManager.exe and selected my mod. Then I clicked on build. And it took a few seconds to finished. Then I selected the Archive menu and Clicked on Build also. And both process worked successfully. Though each timed I tried Friday, no matter the steps I used, whenever I clicked on Build from the menu, it would ask me if I wanted to delete all unrelated files or keep them… and whether I chose to keep them or delete them it didn’t work. (I think those files were all related to Dawn of Masteries). Though this time it didn’t asked at all. So I thought maybe it worked this time. But it didn’t. (See picture 06) 
And in picture 07 you can see the “records” folders has been created with the Creatures and Items as subfolders, etc. So this part seemed to have worked.
So finally, when I launched the game I could select the Test map it created. And the commands worked, my XP raised significantly higher and I had 8 attributes points. So this part worked. But the Dawn of Masteries mod is not incorporated, since my stash is the same size as the normal main campaign, while in Dawn of Masteries its way larger. And other few stuff are not showing.

**Log File** 

And below is what my log file showed since I couldnt find a way to attach any file here:


WARNING: No subdirectory is given for additional source. All subdirectories will be scanned.
Scanning: included mods
Scanning: C:\Program Files (x86)\Steam\steamapps\common\Grim Dawn\mods\dom\database\records\
Scanning: C:\Program Files (x86)\Steam\steamapps\common\Grim Dawn\database\records\creatures
Scanning: C:\Program Files (x86)\Steam\steamapps\common\Grim Dawn\database\records\game
Scanning: C:\Program Files (x86)\Steam\steamapps\common\Grim Dawn\database\records\items
Scanning: C:\Program Files (x86)\Steam\steamapps\common\Grim Dawn\database\records\proxies
Scanning: C:\Program Files (x86)\Steam\steamapps\common\Grim Dawn\database\records\interactive
Running command: AdjustGoldDrop
Running command: AdjustExpRequirement
Running command: SetAttributePointsPerLevel





So let me know where you think I made a mistake. So thank you so much, so much for your time!

JP

**Comment by azakhi** [comment]
Thanks for detailing process @balryon 
I cannot see the pictures you mention but I will try to clarify couple things so you can correct if necessary.

First of all, let me explain to you how would modifying another mod work because game doesn't allow loading 2 mods at the same time. So normally a mod is simply game's base files modified. When you want to modify another mod with this tool, it first checks the mod to see if it is overriding (modifying) game's base files and if that is the case, uses those instead. After you run the tool, it gives you **ONLY** modified files. Normally this is fine because game already has base files and needs only modified files. But when you modify another mod, there might be files modified by that mod but not with the tool. So you **can't** use just the output of the tool. You need to combine them.

Here are step by step process to do that.

1- I highly recommend a clean install. Re-install the game and the Dawn of Masteries mod.
2- You do need to unpack _dom.arz_ to have modified files. Here is how you can do it:
- On windows, search for **Command Prompt**, right click -> Run As Administrator
- Copy and paste this command (you can paste with right click): `cd "C:\Program Files (x86)\Steam\steamapps\common\Grim Dawn"`
- Hit enter, now the command line should have switched to that folder. You can see that on the left side of cursor.
- Run this command same way: `ArchiveTool.exe mods\dom\database\dom.arz -database "%cd%\mods\dom\database"`
- After this check if there is a Records folder there and if it has files.

3- You should create your own mod. It will be cleaner. Suppose you created it and named it **dommodified**
4- You should define `$ModDirectory` with your mod's path. In above case, it would be `C:\Program Files (x86)\Steam\steamapps\common\Grim Dawn\mods\dommodified\` . This is needed to output all the modified files in this mod's folder.
5- If you don't want the scanning to take too much, you can define `$AdditionalSubDirectories` like in the example config files. So in your case, copy and paste this under the `$SubDirectories` list, above `$Commands`:
```
$AdditionalSubDirectories
creatures
game
items
proxies
interactive
```
6- **Do not add additional mods that come with this tool, like Stasher**.  This tool cannot combine UI changes so if Dawn of Masteries and those other mods are changing same thing, it might end up broken. I don't see these in your process but wanted to remind you.
7- Run the tool and wait for it to be done. This will put modified files under `C:\Program Files (x86)\Steam\steamapps\common\Grim Dawn\mods\dommodified\database\records\` . You can check after to see if there are files here and how many of them.
8- Now this is the important step. Combining two mods. Copy everything under `C:\Program Files (x86)\Steam\steamapps\common\Grim Dawn\mods\dom\` and paste them to `C:\Program Files (x86)\Steam\steamapps\common\Grim Dawn\mods\dommodified\`. **When asked if you want to override existing files, select NO**. You **should not** override `dommodified` files.
9- Delete **dom.arz** file under `C:\Program Files (x86)\Steam\steamapps\common\Grim Dawn\mods\dommodified\database`. This came from copying and has unmodified files.
10- Compile your mod following steps here: https://github.com/azakhi/GDModdingTool/wiki
11- Check `C:\Program Files (x86)\Steam\steamapps\common\Grim Dawn\mods\dommodified\database` folder to see if there is a **dommodified.arz** file there.
12- If the file is there, you can start the game and select **dommodified** as your mod. Let me know how it goes.

Good luck!

**Comment by PathForgingStudios** [comment]
Thank you so much for clarifying everything. Im quite a newbie regarding modding so thanks for explaining the process. Everything seemed to work well except that the UI was completely messed up and unclickable. So my guess comes from the fact that your tool cannot combine UI changes is that correct? 

Besides that everything else seemed to work perfectly. The only few things I realized during the whole process was that, when I copied the dom files to the dommodified folder, it never asked me to overwrite anything. Also, after building my new mod from the Asset Manager, it says there was 21 errors and 0 warnings. But in the logs I couldnt find any errors.

So what would you recommend to fix the UI issue?

Thanks again a lot. I also realized there is a place in the Crate forum where people talk about modding so I will probably check this out later this week. it might also help me familiarize myself with modding.

![07](https://user-images.githubusercontent.com/108500082/177281591-ac10f378-56f1-4c55-ad26-104843992f0b.jpg)
![06](https://user-images.githubusercontent.com/108500082/177281596-4e098d06-2ee7-4bb1-861d-6062d1546360.jpg)
![05](https://user-images.githubusercontent.com/108500082/177281597-84e22fbb-2d24-417b-8a29-a3f6ca538176.jpg)
![04](https://user-images.githubusercontent.com/108500082/177281598-799e4e17-f455-4c88-89a5-988892000b4c.jpg)
![03](https://user-images.githubusercontent.com/108500082/177281600-04a585aa-f806-485c-9279-60f0033bd27f.jpg)
![02](https://user-images.githubusercontent.com/108500082/177281601-de7f23e3-0529-4364-b9cc-27b6506d0bcf.jpg)
![01](https://user-images.githubusercontent.com/108500082/177281604-90ee2b80-d4b5-44d7-9a55-90daaf7b8852.jpg)
![00](https://user-images.githubusercontent.com/108500082/177281607-cc51443b-4145-4859-b9c1-d615cc39f675.jpg)

**Comment by azakhi** [comment]
@balryon 

> So my guess comes from the fact that your tool cannot combine UI changes is that correct?

This would be an issue only if you use the mentioned extra mods that come with the tool, like Stasher. I don't see that in your config file so shouldn't have been an issue.

> The only few things I realized during the whole process was that, when I copied the dom files to the dommodified folder, it never asked me to overwrite anything. Also, after building my new mod from the Asset Manager, it says there was 21 errors and 0 warnings. But in the logs I couldnt find any errors.

This doesn't sound right. There should have been files to override.

I will install Grim Dawn and the Dawn of Masteries mod to try it myself and see if there is something I missed.

**Comment by azakhi** [comment]
Hello again @balryon 
I installed the game and the Dawn of Masteries mod and followed the steps I described.
There being no files to override is normal. Since your test configuration changes only 12 files, none were common between that and Dawn of Masteries.
Errors during the build however is not normal. I checked them and it seems Dawn of Masteries has it is own templates, you can download those on Nexus website and should put them under `Grim Dawn\database\templates`
After this you can build without errors. However for some reason assets are not loading properly. What I did to solve it is, after **dommodified** was built, I copied `dommodified.arz` into `Grim Dawn\mods\dom\database`, rename `dom.arz` to something else and `dommodified.arz` to `dom.arz`. This way playing Dawn of Masteries with my custom changes worked for me.

**Comment by PathForgingStudios** [comment]
Hey @azakhi ! Thank you so much for taking the time to do this. It finally worked though I have to play the Dawn of Masteries custom map instead of my dommodified map which is fine I guess. Its late here so I didn't understand everything fully but at least it works!! Ill review the whole process later this week.

Also, is it possible to change the base movement speed of my character with a command line? If so do you know what name the command is?

And finally, Im willing to give you a 30-40$ gift since you saved me many hours of trial and errors and you now provided me with many hours of fun! Thanks! So is there any way I can send you money through Paypal? If so, is there any place I can chat with you more privately instead of here?

**Comment by azakhi** [comment]
@balryon 
I am glad it worked, happy to help.
I am not aware of a way to change base character movement speed. I vaguely remember looking into it while making this tool but I can't remember why I didn't add it or if it was even possible through modifying database files.
Thanks for offer. However I decided not to accept any money when I worked on this project. If you would like, please pick a charity and donate there. Or if you would like to help another wonderful person to do what they love, please check out https://www.twitch.tv/amellerose .

**Comment by PathForgingStudios** [comment]
Alright thank you :) ! I finally found how to change character speed, which is by openning gameengine.dbr or maybe another file, through AssetManager.exe and modify it there. Thanks again for everything! Cheers!
